const internshipData = [
  {
    id: 1,
    title: "Web Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 2,
    title: "Software Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 3,
    title: "Web Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 4,
    title: "Software Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 5,
    title: "Web Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 6,
    title: "Software Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 7,
    title: "Web Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 8,
    title: "Software Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 9,
    title: "Web Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 10,
    title: "Software Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 11,
    title: "Web Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 12,
    title: "Software Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,    
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 13,
    title: "Web Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  {
    id: 14,
    title: "Software Development Intern",
    company: "TechCo",
    category: "Development",
    payment: 50000,
    duration: "3 months",
    location: "Remote",
  },
  // Add more sample data here
];

export default internshipData;
